const MCP_TOOL_NAMES = [
  'data_source_list',
  'data_source_describe',
  'data_source_read',
  'data_source_profile',
  'catalog_explore_personal',
  'catalog_list',
  'catalog_describe',
  'catalog_save_personal',
  'catalog_reset_personal',
  'catalog_save_canonical',
  'catalog_promote_personal',
  'table_filter_select',
  'table_derive',
  'table_join',
  'table_aggregate',
  'table_join_aggregate',
  'table_sort_limit',
  'artifact_preview',
  'csv_export',
  'workflow_validate',
  'workflow_list',
  'workflow_get',
  'workflow_save',
  'workflow_archive',
  'workflow_execute',
] as const

export const MCP_TOOL_COUNT = MCP_TOOL_NAMES.length
export const MCP_DATA_SOURCE_ACCESS = 'read-only' as const
